pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Instalar dependencias') {
            steps {
                dir('server') {
                    bat 'npm install'
                }
            }
        }

        stage('Pruebas API (Newman)') {
            steps {
                dir('server') {
                    bat 'npm run test:api'
                }
            }
        }
    }

    post {
        always {
            // Guardar artefacto HTML desde server/reportes
            archiveArtifacts artifacts: 'server/reportes/gestTeam-api.html', fingerprint: true

            // Publicar reporte HTML
            publishHTML(target: [
                reportDir   : 'server/reportes',
                reportFiles : 'gestTeam-api.html',
                reportName  : 'GestTeam – Pruebas Backend'
            ])
        }
    }
}
